### ISSUE TITLE
KafkaUnknownConfigurationKey: No such configuration property: \"auto.offset.reset\"

### ISSUE THREAD

**Issue by manojgudi** [cosbynator/haskakafka#30]
I get this error when I pass  ("auto.offset.reset", "latest")  as extra kafka conf properties in runConsumer function.

librdkafka seems to implement this:
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

Am I missing something?

**Comment by edenhill** [comment]
That's a topic level configuration property.

Den 27 dec. 2016 13:35 skrev "Manoj" <notifications@github.com>:

I get this error when I pass ("auto.offset.reset", "latest") as extra kafka
conf properties in runConsumer function.

librdkafka seems to implement this:
https://github.com/edenhill/librdkafka/blob/master/CONFIGURATION.md

Am I missing something?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/cosbynator/haskakafka/issues/30>, or mute the thread

**Comment by manojgudi** [comment]
Yeah my bad. Sorry for the noise.
